version: "3.9"
services:
  priceservice:
    container_name: PriceApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8083:8083
